name: Test myself

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: adoptopenjdk/openjdk14
      options: -v /opt/java/openjdk/bin
      volumes:
        - /opt/java/openjdk/bin
    steps:
      - uses: actions/checkout@v2

      - name: Print java version
        run: ls /opt/java/openjdk/bin

      - name: Run local action
        uses: ./
