name: Test myself

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container: alpine/git:v2.30.2
    steps:
      - uses: actions/checkout@v2

      - name: Write to a file
        run: echo 'The only difference between a madman and myself is that I am not mad.' >> q.txt

      - name: Read the file
        run: cat q.txt

      - name: Read the file using Docker based action
        uses: ./
