name: Test myself

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container: adoptopenjdk/openjdk14
    steps:
      - uses: actions/checkout@v2

      - name: Write to a file
        run: java -version

      - name: Read the file
        run: cat q.txt

      - name: Read the file using Docker based action
        uses: ./
