name: Test myself

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Print java version
        run: which sam

  abc3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Print java version
        run: echo "ABC"

  abc2:
    needs: abc3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Print java version
        run: echo "ABC 2"
