name: Test myself

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container: adoptopenjdk/openjdk14
    steps:
      - uses: actions/checkout@v2

      - name: Print java version
        run: java -version

      - name: Run local action
        uses: ./
